"""
Generates a self-contained HTML report summarizing a run. The report requires
no JavaScript and no external CSS so it can be attached to a pull request,
committed to a CI artifacts bucket, or emailed directly.
"""

from __future__ import annotations

import html
from pathlib import Path

from src.models import Anomaly, Severity, TestCase

_SEVERITY_ORDER = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]
_SEVERITY_COLORS = {
    Severity.CRITICAL: "#b91c1c",
    Severity.HIGH: "#c2410c",
    Severity.MEDIUM: "#a16207",
    Severity.LOW: "#0369a1",
    Severity.INFO: "#374151",
}


def _esc(text: str) -> str:
    return html.escape(str(text))


def generate_html_report(
    target_url: str,
    anomalies: list[Anomaly],
    test_cases: list[TestCase],
    visited_count: int,
    output_path: str,
) -> str:
    sorted_anomalies = sorted(anomalies, key=lambda a: _SEVERITY_ORDER.index(a.severity))

    anomaly_rows = "\n".join(
        f"""<tr>
        <td><span style="color:{_SEVERITY_COLORS[a.severity]};font-weight:bold">{_esc(a.severity.value.upper())}</span></td>
        <td>{_esc(a.category)}</td>
        <td>{_esc(a.description[:200])}</td>
        <td><a href="{_esc(a.page_url)}">{_esc(a.page_url[:60])}</a></td>
        </tr>"""
        for a in sorted_anomalies
    ) or "<tr><td colspan='4' style='text-align:center;color:#6b7280'>No anomalies detected</td></tr>"

    test_rows = "\n".join(
        f"<tr><td>{_esc(t.id)}</td><td>{_esc(t.title)}</td><td>{len(t.steps)}</td><td>{', '.join(t.tags)}</td></tr>"
        for t in test_cases
    ) or "<tr><td colspan='4' style='text-align:center;color:#6b7280'>No test cases generated</td></tr>"

    report = f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Agentic Testing Report</title>
<style>
body {{ font-family: -apple-system, system-ui, sans-serif; max-width: 960px; margin: 2rem auto; padding: 0 1rem; color: #1f2937; }}
h1, h2 {{ border-bottom: 2px solid #e5e7eb; padding-bottom: .5rem; }}
.cards {{ display: flex; gap: 1rem; flex-wrap: wrap; margin: 1rem 0; }}
.card {{ background: #f9fafb; border: 1px solid #e5e7eb; border-radius: .5rem; padding: 1rem 1.25rem; flex: 1; min-width: 140px; }}
.card h3 {{ margin: 0 0 .25rem; font-size: .85rem; color: #6b7280; text-transform: uppercase; letter-spacing: .03em; }}
.card p {{ margin: 0; font-size: 1.75rem; font-weight: 700; }}
table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
th, td {{ padding: .5rem .75rem; text-align: left; border-bottom: 1px solid #e5e7eb; font-size: .9rem; }}
th {{ background: #f3f4f6; font-weight: 600; position: sticky; top: 0; }}
a {{ color: #2563eb; text-decoration: none; }} a:hover {{ text-decoration: underline; }}
</style>
</head>
<body>
<h1>Agentic Testing Report</h1>
<p>Target: <a href="{_esc(target_url)}">{_esc(target_url)}</a></p>

<div class="cards">
  <div class="card"><h3>States visited</h3><p>{visited_count}</p></div>
  <div class="card"><h3>Anomalies</h3><p>{len(anomalies)}</p></div>
  <div class="card"><h3>Test cases</h3><p>{len(test_cases)}</p></div>
</div>

<h2>Anomalies</h2>
<table>
<thead><tr><th>Severity</th><th>Category</th><th>Description</th><th>Page</th></tr></thead>
<tbody>{anomaly_rows}</tbody>
</table>

<h2>Generated Test Cases</h2>
<table>
<thead><tr><th>ID</th><th>Title</th><th>Steps</th><th>Tags</th></tr></thead>
<tbody>{test_rows}</tbody>
</table>

<footer style="margin-top:2rem;padding-top:1rem;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:.8rem">
Generated by the Agentic Testing Framework
</footer>
</body></html>"""

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(report, encoding="utf-8")
    return output_path
